#!/bin/bash

function updateKernel {
  DIR=$1; IMG=$2; BRANCH=$3
  cd /usr/src/${DIR}
  git reset --merge ${BRANCH}
  rc=$?
  if [[ $rc != 0 ]]; then
    git reset --hard ${BRANCH}
    git apply ../01-enable-additional-cpu-optimizations.patch
    git apply ../02-xattr-user-prefix.patch
  fi
  make -j10
  make modules_install
  cp arch/x86/boot/bzImage /boot/bzImage-${IMG}.efi
}

rm -f /etc/portage/make.conf\~

cp /usr/bin/git-update /usr/src

cd /usr/src/
git pull

cd /lib/firmware
git pull

rm -rf /lib/modules/*

cd /usr/src/linux
git fetch --all --prune

updateKernel linux tip   linus/master
updateKernel drm   drm   airlied/drm-next
updateKernel intel intel intel/drm-tip
updateKernel agd5f agd5f agd5f/drm-next-4.19-wip

git push github --all --force
git push github --tags

cp /usr/src/agd5f/.config       /usr/src/dot_config_adg5f
cp /usr/src/drm/.config         /usr/src/dot_config_drm
cp /usr/src/intel/.config       /usr/src/dot_config_intel
cp /usr/src/linux/.config       /usr/src/dot_config_tip

cd /usr/src
git add .
git commit -m "Git Update `date +%F-%T`"
git push

cd /etc/portage
git pull
git add .
git commit -m "Git Update `date +%F-%T`"
git push

cd /home/fireburn/Mesa
sudo -u fireburn git fetch --all --prune
sudo -u fireburn git push github --all --force
sudo -u fireburn git push github --tags
sudo -u fireburn git push gitlab --all --force
sudo -u fireburn git push gitlab --tags

emerge --sync --quiet
emerge -vDuNt -j5 @world
emerge -vDt -j5 @live-rebuild @preserved-rebuild
eclean-dist --destructive -q
