#!/bin/bash

export PATH=/usr/lib/llvm/12/bin:$PATH

function updateKernel {
  DIR=$1; IMG=$2; BRANCH=$3 LLVM=$4

  if [[ ${LLVM} != "0" ]]; then
    USE_LLVM="LLVM=1 LLVM_IAS=1"
  else
    USE_LLVM=""
  fi

  cd /usr/src/${DIR}
  git rebase ${BRANCH}
  rc=$?
  if [[ $rc != 0 ]]; then
    git rebase --abort
    git am --abort
    git reset --hard ${BRANCH}
    git am ../01-enable-O3-5.7.patch
    git am ../02-enable-additional-cpu-optimizations-5.8.patch
    git am ../03-xattr-user-prefix-r2.patch
#    git am ../04-ntfs3.patch
    git am ../05-amdgpu-revert.patch
  fi
  make $USE_LLVM -j20
  make $USE_LLVM modules_install
  cp arch/x86/boot/bzImage /boot/bzImage-${IMG}.efi
}

rm -f /etc/portage/make.conf\~

cp /usr/bin/git-update /usr/src

cd /usr/src/
git pull

cd /lib/firmware
git pull

rm -rf /lib/modules/*

cd /usr/src/linux
git fetch --all --prune

git push github --all --force
git push github --tags
git push gitlab --all --force
git push gitlab --tags
git push freedesktop --all --force
git push freedesktop --tags

updateKernel agd5f agd5f agd5f/drm-next		1
updateKernel linux tip   linus/master		1
updateKernel drm   drm   airlied/drm-next	1

cp /usr/src/agd5f/.config       /usr/src/dot_config_adg5f
cp /usr/src/drm/.config         /usr/src/dot_config_drm
cp /usr/src/linux/.config       /usr/src/dot_config_tip

cd /usr/src
git add .
git commit -m "Git Update `date +%F-%T`"
git push

cd /etc/portage
git pull
git add .
git commit -m "Git Update `date +%F-%T`"
git push

cd /home/fireburn/Mesa
sudo -u fireburn git fetch --all --prune
sudo -u fireburn git pull
sudo -u fireburn git tag -d R300_DRIVER_0
sudo -u fireburn git tag -d before_upgrade_03_01_05
sudo -u fireburn git tag -d blended_fountain
sudo -u fireburn git tag -d embedded-1-20030120
sudo -u fireburn git tag -d embedded-1-20030224
sudo -u fireburn git tag -d embedded-1-20030305
sudo -u fireburn git tag -d embedded-1-20030324
sudo -u fireburn git tag -d embedded-1-20030417
sudo -u fireburn git tag -d embedded-1-20030502
sudo -u fireburn git tag -d gliding_penguin
sudo -u fireburn git tag -d jump_and_click
sudo -u fireburn git tag -d kw-mesa-1
sudo -u fireburn git tag -d mesa-6_5-20060712
sudo -u fireburn git tag -d mesa_20050504
sudo -u fireburn git tag -d mesa_20050526
sudo -u fireburn git tag -d mesa_20050610
sudo -u fireburn git tag -d mesa_20050715
sudo -u fireburn git tag -d mesa_20060201
sudo -u fireburn git tag -d mesa_20060325
sudo -u fireburn git tag -d mesa_3_1
sudo -u fireburn git tag -d mesa_3_1_beta_3
sudo -u fireburn git tag -d mesa_3_2
sudo -u fireburn git tag -d mesa_3_2_1
sudo -u fireburn git tag -d mesa_3_2_beta_1
sudo -u fireburn git tag -d mesa_3_3
sudo -u fireburn git tag -d mesa_3_4
sudo -u fireburn git tag -d mesa_3_4_1
sudo -u fireburn git tag -d mesa_3_4_2
sudo -u fireburn git tag -d mesa_3_5
sudo -u fireburn git tag -d mesa_4_0
sudo -u fireburn git tag -d mesa_4_0_1
sudo -u fireburn git tag -d mesa_4_0_2
sudo -u fireburn git tag -d mesa_4_0_3
sudo -u fireburn git tag -d mesa_4_0_4
sudo -u fireburn git tag -d mesa_4_1
sudo -u fireburn git tag -d mesa_5_0
sudo -u fireburn git tag -d mesa_5_0_1
sudo -u fireburn git tag -d mesa_6_3
sudo -u fireburn git tag -d mesa_6_3_1
sudo -u fireburn git tag -d mesa_6_3_1_1
sudo -u fireburn git tag -d mesa_6_3_2
sudo -u fireburn git tag -d mesa_6_4
sudo -u fireburn git tag -d mesa_6_4_1
sudo -u fireburn git tag -d mesa_6_4_2
sudo -u fireburn git tag -d mesa_6_5
sudo -u fireburn git tag -d mesa_6_5_1
sudo -u fireburn git tag -d mesa_6_5_2
sudo -u fireburn git tag -d mesa_texman_20060210
sudo -u fireburn git tag -d noisy_cube
sudo -u fireburn git tag -d red_tinted_cube
sudo -u fireburn git tag -d rotating_gears
sudo -u fireburn git tag -d shimmering_gears
sudo -u fireburn git tag -d start
sudo -u fireburn git tag -d texman_0_1_20060325
sudo -u fireburn git tag -d texman_0_1_20060330
sudo -u fireburn git tag -d texman_0_1_20060621
sudo -u fireburn git tag -d texman_0_1_20060705
sudo -u fireburn git tag -d texman_0_1_pre_ttm
sudo -u fireburn git tag -d texmem_0_2_20060912
sudo -u fireburn git tag -d texmem_0_3_20060923
sudo -u fireburn git tag -d texmem_0_3_20060929
sudo -u fireburn git tag -d the_perfect_frag
sudo -u fireburn git tag -d trunk_20040329
sudo -u fireburn git tag -d unichrome-last-xinerama
sudo -u fireburn git tag -d vtx-0-2-21112003-freeze
sudo -u fireburn git tag -d vtx-0-2-24112003
sudo -u fireburn git push github --all --force
sudo -u fireburn git push github --tags
sudo -u fireburn git push gitlab --all --force
sudo -u fireburn git push gitlab --tags

cd /usr/portage
emerge --sync --quiet
git push gitlab --all --force
git push github --all --force
emerge -vDuNt -j10 @world
emerge -vDt -j10 @live-rebuild @preserved-rebuild
emerge --depclean -a
eclean-dist --destructive -q
