#!/bin/bash

function kernelMerge {
  git reset --merge ${BRANCH}
  rc=$?
  if [[ $rc != 0 ]]; then
    git reset --hard ${BRANCH}
    git apply ../01-enable-additional-cpu-optimizations.patch
    git apply ../02-xattr-user-prefix.patch
  fi
}

function updateKernel {
  DIR=$1; IMG=$2; BRANCH=$3
  cd /usr/src/${DIR}
  kernelMerge
  make -j10
  make modules_install
  cp arch/x86/boot/bzImage /boot/bzImage-${IMG}.efi
}

rm -rf /lib/modules/*

cd /usr/src/linux
git fetch --all

updateKernel linux tip   linus/master
updateKernel drm   drm   airlied/drm-next
updateKernel intel intel intel/drm-intel-nightly
updateKernel agd5f agd5f agd5f/drm-next-4.12-wip

git push github --all --force
git push github --tags
