#!/bin/bash
rm -f /etc/portage/make.conf\~
cp /usr/bin/git-update /usr/src
cd /usr/src/
git pull
cp /usr/src/agd5f/.config	/usr/src/dot_config_adg5f
cp /usr/src/drm/.config		/usr/src/dot_config_drm
cp /usr/src/intel/.config	/usr/src/dot_config_intel
cp /usr/src/linux/.config	/usr/src/dot_config_tip
git add .
git commit -m "Git Update `date +%F-%T`"
git push
cd /etc/portage
git pull
git add .
git commit -m "Git Update `date +%F-%T`"
git push
cd /lib/firmware
git pull
cd /usr/src/linux
git fetch --all
git reset --merge linus/master
make -j5 &
cd /usr/src/drm
git reset --merge airlied/drm-next
make -j5 &
cd /usr/src/intel
git reset --merge intel/drm-intel-nightly
make -j5
cd /usr/src/agd5f
git reset --merge agd5f/drm-next-4.12-wip
git push github --all --force
git push github --tags
cd /home/fireburn/mesa
sudo -u fireburn git fetch --all
sudo -u fireburn git pull
sudo -u fireburn git push github --all --force
emerge --sync --quiet
emerge -vDuNt -j5 @world
emerge -vDt -j5 @live-rebuild @preserved-rebuild
prelink -af
eclean-dist --destructive -q
